name: mi_card
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf
  
  - family: SourceSans3
    fonts:
    - asset: fonts/SourceSans3-Regular.ttf
